title: "Lakhan Mandloi"
description: "3.5 Years Experienced Full Stack Developer with a demonstrated history of working in the Web Development industry. Skilled in UI Development , DevOps and Backend Development. Also have interest in Analytics, SEO and Security."
keywords:
author: "Lakhan Mandloi"
language: "en-Gb"
logo: "/images/lakhan-mandloi-circular.png"
email: "lakhansinghmandloi1@gmail.com"
website: "https://lakhanmandloi.github.io/"
mobile: ""
github: "https://github.com/lakhanmandloi/"
linkedin: "https://www.linkedin.com/in/lakhanmandloi/"
twitter: "https://twitter.com/Lakhan_Mandloi"
facebook: "https://www.facebook.com/Lakhansinghmandloi1"
youtube: ""
ga: "UA-121628963-1"

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
