title: 'लखन मंडलोई'
description: 'एक गौरवान्वित भारतीय और ६+ वर्ष अनुभवी सॉफ्टवेयर अभियान्ता'
keywords:
author: 'लखन मंडलोई'
language: 'hi-IN'
logo: '/images/lakhan-mandloi-circular.png'
email: ''
website: 'https://lakhanmandloi.github.io/'
mobile: ''
github: 'https://github.com/lakhanmandloi/'
linkedin: 'https://www.linkedin.com/in/lakhanmandloi/'
twitter: 'https://twitter.com/Lakhan_Mandloi'
facebook: 'https://www.facebook.com/Lakhansinghmandloi1'
youtube: ''
ga: 'UA-121628963-1'

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

defaults:
  - scope:
      path: 'experiments'
    values:
      layout: 'entry'
      type: 'experiment'
      comments: true
  - scope:
      path: 'blogs'
    values:
      layout: 'entry'
      type: 'blog'
      comments: true
